


[[redirects]]
  from = '/*'
  to = '/blog/404'
  status = 404

[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  branches = ['main', 'dev', 'feat/add-algolia']
  pathPrefix = "/blog"
  renderJavaScript = true
# customDomain = "guidedogs.org.uk"



#[[headers]]
#  for = "*" # js files should be set this way
#  [headers.values]
#    Cache-Control = "public, max-age=0, must-revalidate"
   

#[[redirects]]
#  from = '/404'
#  to = 'https://www.guidedogs.org.uk/404/'
#  status = 404

#[[redirects]]
#    from = "/*"
#    to = "https://www.guidedogs.org.uk/404/"
#    status = 404


# Proxy for media items
#[[redirects]]
#	from = '/redirect/*'
#	to = 'https://www.guidedogs.org.uk'
#	status = 200

[[redirects]]
  from = '/clone'
  to = 'https://gd-dev-origin.guidedogs.org.uk/how-you-can-help/how-your-school-or-youth-group-can-help/stem-projects/stem-thank-you'
  status = 200
  force = true
  [redirects.headers]
      Authorization = "Basic Z3VpZGVkb2dzOmM4N2J0R0hRWUhVWENqc1FNQTV5dHRKWg=="	
	

#[[redirects]]
#  from = '/aboutus'
#  to = 'https://www.guidedogs.org.uk/about-us/'
#  status = 200
#  force = true
 

#[[redirects]]
#  from = "/api-fe/*"
#  to = "/.netlify/functions/:splat"
#  status = 200
  
