[[headers]]
  for = "*" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
   



# Proxy for media items
[[redirects]]
	from = '/redirect/*'
	to = 'https://www.guidedogs.org.uk'
	status = 200

[[redirects]]
  from = '/clone'
  to = 'https://gd-dev-origin.guidedogs.org.uk/how-you-can-help/how-your-school-or-youth-group-can-help/stem-projects/stem-thank-you'
  status = 200
  force = true
  [redirects.headers]
      Authorization = "Basic Z3VpZGVkb2dzOmM4N2J0R0hRWUhVWENqc1FNQTV5dHRKWg=="	
	

[[redirects]]
  from = '/aboutus'
  to = 'https://www.guidedogs.org.uk/about-us/'
  status = 200
  force = true
 

[[redirects]]
  from = "/api-fe/*"
  to = "/.netlify/functions/:splat"
  status = 200
  
# Rewrite for blog
[[redirects]]
	from = '/blog/*'
	to = 'https://gracious-golick-56c5e9.netlify.app/blog/:splat'
	status = 200
