
# Proxy for media items
[[redirects]]
	from = '/redirect/*'
	to = 'https://www.guidedogs.org.uk'
	status = 200

	

[[redirects]]
  from = "/api-fe/*"
  to = "/.netlify/functions/:splat"
  status = 200
  
